### ISSUE TITLE
Yo

### ISSUE THREAD

**Issue by johnnycrq** [abelDev/LOL-Chat#1]
I would like to contribute to this project. Also, the app is crashing at the start.
I can help you to fix bugs, do the landscape and portrait layouts for more devices, refactor the code for easy reading, etc. I was about to restart a new client of mine for lol but as it seems, this one is already working so i would like to contribute if possible. cann u add me?

**Comment by foxlet** [comment]
You could make a fork, do some commits, and we can look into the changes you wish make.

**Comment by johnnycrq** [comment]
fine. tell me what is the todo list and what needs to be fixed

**Comment by tesfaye** [comment]
Hello, can you please send the crash log and what sever are you using? I'll update the todo list readme with more items.

**Comment by johnnycrq** [comment]
```
Process: com.tesfaye.lolchat, PID: 1132
java.lang.NullPointerException
        at com.tesfayeabel.lolchat.ChatService$1.run(ChatService.java:111)
        at java.lang.Thread.run(Thread.java:841)
```

**Comment by tesfaye** [comment]
Did you supply a valid Riot api key in strings.xml? Also, what server are you using?

**Comment by johnnycrq** [comment]
yo the api key was expired i have fixed it. i took a look at the code and did some re-factoring first. it has too much boilerplate code, i re-coded every view injection and reduced some significant lines of code. can u give me commit rights plz?

**Comment by tesfaye** [comment]
For now, could you please submit a pull request as I'd like to review the code.

**Comment by johnnycrq** [comment]
hm maybe later. i'll have to pull request and merge the changes, because i have already imported the project without pulling it up. anyway, your service should not have the responsibility to start an activity. if it ever needs to restart, it will bug your app.
